### PR TITLE
Build on Jitpack.io

### PR DESCRIPTION
**Pull request by am3n**
Changes were made in the version of Gradle, JDK, Kotlin and Gradle scripts so that we can build the library with the jitpack.io service like this: [am3n/pattern-lock](https://jitpack.io/#am3n/pattern-lock/1.0.1)

### CODE REVIEW

**Comment by harri35** [comment]
Hei @am3n !

Thanks for the PR. Do I understand correctly that the goal of your PR is to make this version of the library publishable with minimal effort? And you would still like to consume this library, not your own fork?

I guess this is one way to go. The readme should be updated to have an example of how to consume the library from Jitpack.io.

To be honest, we have been using Maven Central for our open-source. So an alternative would be that I'll just add Maven Central publishing to this. A little effort from our side, but if we actually want to officially provide this fork then worth the effort to have the same publishing for all. I'll discuss it with the Mobi Lab Android community.

What is your timeline for the answer - are you waiting behind this PR atm and are blocked with your own work? I guess if you update the readme then I could merge this PR regardless and if we decide for Maven Central then later move it ..

**Comment by am3n** [comment]
Thank you @harri35
No, I currently use the Jitpack build from my fork in my project.
But I felt that your development on this library is worth to be made available under your name in Maven or Jitpack.
And this matter is up to you, I have no insistence to accept my pull request But if you want, I can make the desired changes in Readme.
Thanks.

**Comment by harri35** [comment]
Hei @am3n!

I discussed this with our team. We do not need this fork in the long run and do not want to take the maintenance for this library from the original author. 

So, if you actively need this library and have already published it from your own fork, maybe it would be better if we deprecate our fork, update the README (to link to yours), and forward any future things to your fork? And from your side, you only need to update your readme to point any devs who want to use it to the artefacts you published.
What do you think?

**Comment by am3n** [comment]
Hi @harri35
Good, thanks for your reply, it’s my pleasure

**Pull request closed without merging**
